env: "dev"
storage_path:
    POSTGRES_PASSWORD: "123456"
    POSTGRES_HOST: "localhost"
    POSTGRES_USER: "postgre"
    POSTGRES_DB: "postgre"
    POSTGRES_PORT: "5432"
grpc:
  port: 44044
  timeout: 1h

secret: "dasdasdd"
  